"""
Django settings for Aquraim project.

Generated by 'django-admin startproject'.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m66sff%rk($7yh+rq20w1hmx(og(6yqq#*k=w^ba+m#)n735z6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'Aquraimadmin',
    'Aquraimuser',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Aquraim.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR /'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Aquraimuser.context_processors.shop',
            ],
        },
    },
]

WSGI_APPLICATION = 'Aquraim.wsgi.application'


# =========================
# DATABASE
# =========================
# Default: SQLite (works out of the box, no setup).
# MySQL: set USE_MYSQL=1 (and optionally DB_NAME / DB_USER / DB_PASSWORD / DB_HOST / DB_PORT)
#        and `pip install mysqlclient`.
if os.environ.get('USE_MYSQL'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'world_name'),
            'USER': os.environ.get('DB_USER', 'root'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'babin'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '3306'),
            'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"},
        }
    }
else:
    DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': BASE_DIR / 'db.sqlite3'}}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files

STATIC_URL = 'static/'


# Email

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom admin panel (/aquraimadmin) credentials - override with env vars in production
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'babinjose@gmail.com')
ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD', 'babinjose')
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Map Django message levels to Bootstrap alert classes (error -> danger)
MESSAGE_TAGS = {message_constants.ERROR: 'danger'}

# Uploaded images (profile photos, categories, products, blogs) must be under 5 MB
MAX_UPLOAD_MB = 5
DATA_UPLOAD_MAX_MEMORY_SIZE = 12 * 1024 * 1024

# Shown on the Contact / About pages and footer - edit to your real details
SITE_NAME = 'Aquatic Life'
SITE_EMAIL = os.environ.get('SITE_EMAIL', 'babinjose@gmail.com')
SITE_PHONE = os.environ.get('SITE_PHONE', '+91 00000 00000')
SITE_ADDRESS = os.environ.get('SITE_ADDRESS', 'Your shop address, City, State, India')
